### ISSUE TITLE
Exception: Serialization of Closure is not allowed

### ISSUE THREAD

**Issue by daltonrooney** [madebyraygun/craft-block-loader#11]
@vanrez-nez This looks like it's being triggered by the `$linkfield->getUrl()` method in Hyper. (Seen in Featured Cards block in MSA) The only workaround seems to be to disable caching on the block.

```
Exception: Serialization of 'Closure' is not allowed in /var/www/html/craft/vendor/madebyraygun/craft-block-loader/src/base/ContextCache.php:29
Stack trace:
#0 /var/www/html/craft/vendor/madebyraygun/craft-block-loader/src/base/ContextCache.php(29): serialize(Array)
#1 /var/www/html/craft/vendor/madebyraygun/craft-block-loader/src/base/ContextCacheSet.php(65): madebyraygun\blockloader\base\ContextCache::set(Object(craft\elements\Entry), Object(Illuminate\Support\Collection))
#2 /var/www/html/craft/vendor/madebyraygun/craft-block-loader/src/base/BlocksProvider.php(28): madebyraygun\blockloader\base\ContextCacheSet->write()
#3 /var/www/html/craft/vendor/madebyraygun/craft-block-loader/src/behaviors/BlocksLoaderBehavior.php(17): madebyraygun\blockloader\base\BlocksProvider::extractBlockDescriptors(Object(craft\elements\Entry), 'contentBlocks')
#4 [internal function]: madebyraygun\blockloader\behaviors\BlocksLoaderBehavior->blocksFromField('contentBlocks')
#5 /var/www/html/craft/vendor/yiisoft/yii2/base/Component.php(305): call_user_func_array(Array, Array)
#6 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(2372): yii\base\Component->__call('blocksFromField', Array)
#7 /var/www/html/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1754): craft\base\Element->__call('blocksFromField', Array)
#8 /var/www/html/craft/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'blocksFromField', Array, 'method', false, false, false, 17)
#9 /var/www/html/craft/storage/runtime/compiled_templates/2a/2ad8a12e0d6610103df0638b31a72598.php(104): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\Entry), 'blocksFromField', Array, 'method', false, false, false, 17)
#10 /var/www/html/craft/vendor/twig/twig/src/Template.php(437): __TwigTemplate_79311f28563026d799c9c90b5c624aa5->block_body(Array, Array)
#11 /var/www/html/craft/storage/runtime/compiled_templates/a4/a4808056a87af6c30881246a6cd55a82.php(104): Twig\Template->yieldBlock('body', Array, Array)
#12 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_0e821eab71797493dc511d80837178a9->doDisplay(Array, Array)
#13 /var/www/html/craft/storage/runtime/compiled_templates/2a/2ad8a12e0d6610103df0638b31a72598.php(59): Twig\Template->yield(Array, Array)
#14 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_79311f28563026d799c9c90b5c624aa5->doDisplay(Array, Array)
#15 /var/www/html/craft/storage/runtime/compiled_templates/0a/0ad31bb7b464669201b8d4718f960a33.php(53): Twig\Template->yield(Array)
#16 /var/www/html/craft/vendor/twig/twig/src/Template.php(393): __TwigTemplate_8fdae563aaa5917546963e9d8e8a791d->doDisplay(Array, Array)
#17 /var/www/html/craft/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#18 /var/www/html/craft/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#19 /var/www/html/craft/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#20 /var/www/html/craft/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#21 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(500): Twig\Environment->render('pages/entry', Array)
#22 /var/www/html/craft/vendor/craftcms/cms/src/web/View.php(553): craft\web\View->renderTemplate('pages/entry', Array)
#23 /var/www/html/craft/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('pages/entry', Array, 'site')
#24 /var/www/html/craft/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#25 /var/www/html/craft/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#26 /var/www/html/craft/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#27 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#28 /var/www/html/public/index.php(26): yii\base\Application->run()
#29 {main}
```

**Comment by daltonrooney** [comment]
Additional case: `Serialization of 'finfo' is not allowed` at the same location (ContextCache.php:29).

Triggered on the MSA homepage during Dokku staging deployment. The `finfo` object comes from the image transform pipeline when SEOMate calls `Asset::getUrl()` with a transform. Stack trace:

```
[Exception] Serialization of 'finfo' is not allowed
#0 craft/vendor/madebyraygun/craft-block-loader/src/base/ContextCache.php(29): serialize()
#1 craft/vendor/madebyraygun/craft-block-loader/src/base/ContextCacheSet.php(72): ContextCache::set()
#2 craft/vendor/madebyraygun/craft-block-loader/src/base/BlocksProvider.php(26): ContextCacheSet->write()
...
#6 craft/vendor/vaersaagod/seomate/src/services/MetaService.php(302)
#5 craft/vendor/craftcms/cms/src/elements/Asset.php(2175): getUrl()
#4 craft/vendor/craftcms/cms/src/elements/Asset.php(2247): _url()
#3 craft/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(151): getTransformUrl()
```

The underlying issue is that `ContextCache::set()` calls `serialize()` on the context array which may contain non-serializable PHP objects (`Closure`, `finfo`, etc.) that were attached during template rendering.

Only affects the first cold-cache request; subsequent requests succeed.
